# Generated by Django 5.1.4 on 2025-01-21 05:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('laundryapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='password',
        ),
        migrations.RemoveField(
            model_name='worker',
            name='password',
        ),
    ]
