# Generated by Django 5.1.4 on 2025-01-21 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laundryapp', '0003_alter_student_user_alter_worker_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='password',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='worker',
            name='password',
            field=models.CharField(default='', max_length=50),
        ),
    ]
