# Generated by Django 5.1.4 on 2025-01-28 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laundryapp', '0004_student_password_worker_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='laundryslip',
            name='issue',
            field=models.TextField(blank=True, null=True),
        ),
    ]
